spring:
  datasource:
    initialize: true
    url: jdbc:mysql://localhost:3306/naver?autoReconnect=true&useSSL=false
    username: root
    password: siddid
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    initial-size: 20
    max-idle: 5
    min-idle: 1
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1

  redis:
    host: 127.0.0.1
    port: 6379
  cache:
    type: redis